export interface VirastarOptions {
  cleanupExtraMarks?: boolean
  cleanupKashidas?: boolean
  cleanupLineBreaks?: boolean
  cleanupRightToLeftMarks?: boolean
  cleanupSpacing?: boolean
  cleanupZeroWidthNonJoiners?: boolean
  decodeHtmlEntities?: boolean
  replaceSuffixSpacing?: boolean
  normalizeEllipsis?: boolean
  normalizeEndOfLines?: boolean
  normalizeJalaliDates?: boolean
  normalizeKashidas?: boolean
  normalizeMarkDownBraces?: boolean
  normalizeMarkDownLists?: boolean
  normalizeThreeDots?: boolean
  preserveCurlyBraces?: boolean
  preserveFrontMatter?: boolean
  preserveHtmlComments?: boolean
  preserveHtmlEntities?: boolean
  preserveHtmlTags?: boolean
  preserveNonBreakingSpaces?: boolean
  preserveSquareBrackets?: boolean
  preserveUris?: boolean
  preserveMarkDownCodeBlocks?: boolean
  removeDiacritics?: boolean
  removeLeadingAndTrailingSpaces?: boolean
  removeSpacingForPunctuations?: boolean
  replaceArabicNumbers?: boolean
  replaceDashes?: boolean
  replaceDiacritics?: boolean
  replaceEnglishNumbers?: boolean
  replaceEnglishQuotes?: boolean
  replaceEnglishQuotesPairs?: boolean
  replaceHamzeh?: boolean
  replaceHamzehArabic?: boolean
  replaceMiscNonPersianChars?: boolean
  replaceMiscSpacing?: boolean
  replaceNumeralSymbols?: boolean
  replacePersianGlyphs?: boolean
  replacePrefixSpacing?: boolean
  replacePunctuations?: boolean
  replaceQuestionMarks?: boolean
  replaceSpacingForBracesAndQuotes?: boolean
  replaceSuffixMisc?: boolean
  skip_markdown_ordered_lists_numbers_conversion?: boolean
}
